lang: en
title: Vegnos
description: Research and education on non-human intelligences or extraterrestrials and the implications these have for the human being. 

markdown: kramdown
theme:
plugins:
    - jekyll-feed
    - jekyll-sitemap

feed:
    posts-limit: 20

defaults: 
    - scope: 
        path: _posts
      values: 
        layout: post
