lang: en
title: Vegnos
description: Research and education on non-human intelligences or extraterrestrials and the implications these have for the human being. 
#baseurl: /vegnos
markdown: kramdown
permalink: pretty
theme:
plugins:
    - jekyll-feed
    - jekyll-sitemap

feed:
    posts-limit: 20

defaults: 
  - scope:
      path: "" # An empty string targets all files in the project
    values:
      layout: "page" # Use the name of your layout file in the _layouts folder without extension
  - scope: 
      path: _posts
    values: 
      layout: post
